// spd/app/frontend-react/src/components/ClusterDashboardTab.tsx
import React, { useState, useEffect, useRef } from 'react';
import { getClusterDashboardData } from '../api';
import type { ClusterDashboardResponse } from '../api';
import { ClusterDashboardBody } from './ClusterDashboardBody';

interface ClusterDashboardTabProps {
    iteration: number;
}

export const ClusterDashboardTab: React.FC<ClusterDashboardTabProps> = ({ iteration }) => {
    const [loading, setLoading] = useState(true);
    const [errorMsg, setErrorMsg] = useState<string | null>(null);
    const [dashboard, setDashboard] = useState<ClusterDashboardResponse | null>(null);

    const [nSamples, setNSamples] = useState(16);
    const [nBatches, setNBatches] = useState(2);
    const [batchSize, setBatchSize] = useState(64);
    const [contextLength, setContextLength] = useState(64);

    const pendingControllerRef = useRef<AbortController | null>(null);

    const fetchDashboard = async () => {
        pendingControllerRef.current?.abort();
        const controller = new AbortController();
        pendingControllerRef.current = controller;

        setLoading(true);
        setErrorMsg(null);

        try {
            console.log("fetching dashboard");
            const data = await getClusterDashboardData({
                iteration,
                n_samples: nSamples,
                n_batches: nBatches,
                batch_size: batchSize,
                context_length: contextLength,
            });
            setDashboard(data);
        } catch (e: any) {
            if (controller.signal.aborted) return;
            setErrorMsg(e?.message ?? String(e));
        } finally {
            if (!controller.signal.aborted) {
                setLoading(false);
            }
        }
    };

    useEffect(() => {
        fetchDashboard();
        return () => {
            pendingControllerRef.current?.abort();
            pendingControllerRef.current = null;
        };
    }, []);

    const refresh = (e: React.FormEvent) => {
        e.preventDefault();
        fetchDashboard().catch((e) => setErrorMsg(e?.message ?? String(e)));
    };

    return (
        <div className="tab-content">
            <div className="toolbar">
                <form className="toolbar-form" onSubmit={refresh}>
                    <label>
                        Samples
                        <input
                            type="number"
                            min={1}
                            value={nSamples}
                            onChange={(e) => setNSamples(parseInt(e.target.value))}
                        />
                    </label>
                    <label>
                        Batches
                        <input
                            type="number"
                            min={1}
                            value={nBatches}
                            onChange={(e) => setNBatches(parseInt(e.target.value))}
                        />
                    </label>
                    <label>
                        Batch Size
                        <input
                            type="number"
                            min={1}
                            value={batchSize}
                            onChange={(e) => setBatchSize(parseInt(e.target.value))}
                        />
                    </label>
                    <label>
                        Context
                        <input
                            type="number"
                            min={1}
                            value={contextLength}
                            onChange={(e) => setContextLength(parseInt(e.target.value))}
                        />
                    </label>
                    <button className="run-button" type="submit">
                        Run
                    </button>
                </form>
            </div>

            {loading ? (
                <div className="status">Loading...</div>
            ) : errorMsg ? (
                <div className="status-error">{errorMsg}</div>
            ) : dashboard ? (
                <ClusterDashboardBody dashboard={dashboard} />
            ) : null}
        </div>
    );
};

// spd/app/frontend/src/lib/components/ClusterDashboardTab.svelte
<script lang="ts">
    import { onDestroy, onMount } from "svelte";
    import { getClusterDashboardData, type ClusterDashboardResponse } from "$lib/api";
    import ClusterDashboardBody from "./ClusterDashboardBody.svelte";

    export let iteration: number;

    let loading = true;
    let errorMsg: string | null = null;
    let dashboard: ClusterDashboardResponse | null = null;

    let nSamples = 16;
    let nBatches = 2;
    let batchSize = 64;
    let contextLength = 64;

    let pendingController: AbortController | null = null;

    async function fetchDashboard() {
        pendingController?.abort();
        const controller = new AbortController();
        pendingController = controller;

        loading = true;
        errorMsg = null;

        try {
            console.log("fetching dashboard");
            dashboard = await getClusterDashboardData({
                iteration,
                n_samples: nSamples,
                n_batches: nBatches,
                batch_size: batchSize,
                context_length: contextLength,
                // signal: controller.signal
            });
        } catch (e: any) {
            if (controller.signal.aborted) return;
            errorMsg = e?.message ?? String(e);
        } finally {
            if (!controller.signal.aborted) {
                loading = false;
            }
        }
    }

    onMount(() => {
        fetchDashboard();
    });

    onDestroy(() => {
        pendingController?.abort();
        pendingController = null;
    });

    function refresh() {
        fetchDashboard().catch((e) => (errorMsg = e?.message ?? String(e)));
    }
</script>

<div class="tab-content">
    <div class="toolbar">
        <form class="toolbar-form" on:submit|preventDefault={refresh}>
            <!-- <label>
                Iteration
                <input type="number" bind:value={iteration} />
            </label> -->
            <label>
                Samples
                <input type="number" min={1} bind:value={nSamples} />
            </label>
            <label>
                Batches
                <input type="number" min={1} bind:value={nBatches} />
            </label>
            <label>
                Batch Size
                <input type="number" min={1} bind:value={batchSize} />
            </label>
            <label>
                Context
                <input type="number" min={1} bind:value={contextLength} />
            </label>
            <button class="run-button" type="submit">Run</button>
        </form>
    </div>

    {#if loading}
        <div class="status">Loading...</div>
    {:else if errorMsg}
        <div class="status-error">{errorMsg}</div>
    {:else if dashboard}
        <ClusterDashboardBody {dashboard} />
    {/if}
</div>

<style>
    .tab-content {
        display: flex;
        flex-direction: column;
        gap: 1rem;
        padding: 1rem;
    }

    .toolbar {
        display: flex;
        flex-wrap: wrap;
        gap: 0.75rem;
        align-items: flex-end;
    }

    .toolbar-form {
        display: flex;
        flex-wrap: wrap;
        gap: 0.75rem;
        align-items: flex-end;
    }

    .toolbar-form label {
        display: flex;
        flex-direction: column;
        gap: 4px;
        font-size: 0.85rem;
        color: #555;
    }

    .toolbar-form input {
        width: 90px;
        padding: 4px 6px;
        border: 1px solid #ced4da;
        border-radius: 4px;
        font-size: 0.85rem;
    }

    .run-button {
        padding: 6px 12px;
        border-radius: 4px;
        border: 1px solid #0d6efd;
        background: #0d6efd;
        color: #fff;
        cursor: pointer;
        font-size: 0.9rem;
    }

    .run-button:hover {
        background: #0b5ed7;
        border-color: #0b5ed7;
    }

    .status {
        color: #333;
    }

    .status-error {
        color: #b00020;
    }
</style>
