// spd/app/frontend-react/components/DisabledComponentsPanel.tsx
"use client";

import { useComponentState } from "@/lib/context/ComponentStateContext";

interface DisabledComponentsPanelProps {
    promptTokens: string[];
    isLoading: boolean;
    onSendAblation: () => void;
    onToggleComponent: (layerName: string, tokenIdx: number, componentIdx: number) => void;
}

export default function DisabledComponentsPanel({
    promptTokens,
    isLoading,
    onSendAblation,
    onToggleComponent
}: DisabledComponentsPanelProps) {
    const { runAblation } = useComponentState();

    const hasDisabledComponents = Object.keys(runAblation).some((layer) =>
        runAblation[layer].some((tokenList) => tokenList.length > 0)
    );

    return (
        <div className="flex-[0_0_300px] p-4 border border-gray-300 rounded bg-gray-50 mt-4">
            <div className="flex justify-between items-center mb-4">
                <h3 className="m-0 text-gray-800 text-lg">Disabled Components</h3>
                <button
                    onClick={onSendAblation}
                    disabled={isLoading}
                    className={`px-4 py-2 text-white rounded text-sm ${
                        isLoading
                            ? "bg-gray-400 cursor-not-allowed"
                            : "bg-orange-600 hover:bg-orange-700"
                    }`}
                >
                    {isLoading ? "Sending..." : "Run with ablations"}
                </button>
            </div>
            {hasDisabledComponents ? (
                <div className="flex flex-col gap-4">
                    {Object.entries(runAblation).map(([layerName, tokenArrays]) =>
                        tokenArrays.map((disabledComponents, tokenIdx) =>
                            disabledComponents.length > 0 ? (
                                <div
                                    key={`${layerName}-${tokenIdx}`}
                                    className="bg-white p-3 rounded border border-gray-300"
                                >
                                    <div className="mb-2 text-sm text-gray-600">
                                        <strong>{promptTokens[tokenIdx]}</strong> in <em>{layerName}</em>
                                    </div>
                                    <div className="flex flex-wrap gap-1">
                                        {disabledComponents.map((componentIdx) => (
                                            <span
                                                key={componentIdx}
                                                className="bg-red-500 text-white px-2 py-1 rounded-xl text-xs cursor-pointer hover:bg-red-600 transition-colors"
                                                onClick={() => onToggleComponent(layerName, tokenIdx, componentIdx)}
                                            >
                                                {componentIdx} ×
                                            </span>
                                        ))}
                                    </div>
                                </div>
                            ) : null
                        )
                    )}
                </div>
            ) : (
                <p className="text-gray-500 italic m-0 text-center">No components disabled yet</p>
            )}
        </div>
    );
}

// spd/app/frontend/src/lib/components/DisabledComponentsPanel.svelte
<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<script lang="ts">
    import { runAblation } from "$lib/stores/componentState";

    export let promptTokens: string[];
    export let isLoading: boolean;
    export let onSendAblation: () => void;
    export let onToggleComponent: (layerName: string, tokenIdx: number, componentIdx: number) => void;

    $: hasDisabledComponents = Object.keys($runAblation).some((layer) =>
        $runAblation[layer].some((tokenList) => tokenList.length > 0)
    );
</script>

<div class="disabled-components-panel">
    <div class="disabled-header-row">
        <h3>Disabled Components</h3>
        <button
            on:click={onSendAblation}
            disabled={isLoading}
            class="ablate-button"
        >
            {isLoading ? "Sending..." : "Run with ablations"}
        </button>
    </div>
    {#if hasDisabledComponents}
        <div class="disabled-list">
            {#each Object.entries($runAblation) as [layerName, tokenArrays]}
                {#each tokenArrays as disabledComponents, tokenIdx}
                    {#if disabledComponents.length > 0}
                        <div class="disabled-group">
                            <div class="disabled-header">
                                <strong>{promptTokens[tokenIdx]}</strong>
                                in
                                <em>{layerName}</em>
                            </div>
                            <div class="disabled-items">
                                {#each disabledComponents as componentIdx}
                                    <span
                                        class="disabled-chip"
                                        on:click={() =>
                                            onToggleComponent(
                                                layerName,
                                                tokenIdx,
                                                componentIdx
                                            )}
                                    >
                                        {componentIdx} ×
                                    </span>
                                {/each}
                            </div>
                        </div>
                    {/if}
                {/each}
            {/each}
        </div>
    {:else}
        <p class="no-disabled">No components disabled yet</p>
    {/if}
</div>

<style>
    .disabled-components-panel {
        flex: 0 0 300px;
        padding: 1rem;
        border: 1px solid #ddd;
        border-radius: 4px;
        background-color: #f8f9fa;
        margin-top: 1rem;
        /* max-height: 500px; */
        /* overflow-y: auto; */
    }

    .disabled-header-row {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 1rem;
    }

    .disabled-components-panel h3 {
        margin: 0;
        color: #333;
        font-size: 1.1rem;
    }

    .ablate-button {
        background-color: #ff6b35;
        padding: 0.5rem 1rem;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 0.9rem;
    }

    .ablate-button:hover:not(:disabled) {
        background-color: #e55a2b;
    }

    .ablate-button:disabled {
        background-color: #cccccc;
        cursor: not-allowed;
    }

    .disabled-list {
        display: flex;
        flex-direction: column;
        gap: 1rem;
    }

    .disabled-group {
        background: white;
        padding: 0.75rem;
        border-radius: 4px;
        border: 1px solid #e0e0e0;
    }

    .disabled-header {
        margin-bottom: 0.5rem;
        font-size: 0.9rem;
        color: #555;
    }

    .disabled-items {
        display: flex;
        flex-wrap: wrap;
        gap: 0.25rem;
    }

    .disabled-chip {
        background: #ff6b6b;
        color: white;
        padding: 0.2rem 0.4rem;
        border-radius: 12px;
        font-size: 0.8rem;
        cursor: pointer;
        transition: background-color 0.2s;
    }

    .disabled-chip:hover {
        background: #ff5252;
    }

    .no-disabled {
        color: #999;
        font-style: italic;
        margin: 0;
        text-align: center;
    }
</style>
