// spd/app/frontend-react/components/MaskCombinePanel.tsx
"use client";

import { useState, useEffect } from "react";
import { useComponentState } from "@/lib/context/ComponentStateContext";
import { api } from "@/lib/api";

interface MaskCombinePanelProps {
    promptId: string;
    onMaskCreated: () => void;
}

export default function MaskCombinePanel({ promptId, onMaskCreated }: MaskCombinePanelProps) {
    const { multiSelectMode, setMultiSelectMode, selectedTokensForCombining, setSelectedTokensForCombining } = useComponentState();
    const [combining, setCombining] = useState(false);
    const [description, setDescription] = useState("");
    const [simulatedL0, setSimulatedL0] = useState<number | null>(null);
    const [simulatedJacc, setSimulatedJacc] = useState<number | null>(null);
    const [simulating, setSimulating] = useState(false);

    const layersWithSelections = Array.from(
        new Set(selectedTokensForCombining.map((token) => token.layer))
    );

    useEffect(() => {
        if (selectedTokensForCombining.length > 0 && layersWithSelections.length === 1) {
            simulateMergeL0();
        } else {
            setSimulatedL0(null);
            setSimulatedJacc(null);
        }
    }, [selectedTokensForCombining]);

    const toggleMultiSelectMode = () => {
        setMultiSelectMode(!multiSelectMode);
        if (multiSelectMode) {
            setSelectedTokensForCombining([]);
            setSimulatedL0(null);
            setSimulatedJacc(null);
        }
    };

    const clearSelections = () => {
        setSelectedTokensForCombining([]);
        setSimulatedL0(null);
        setSimulatedJacc(null);
    };

    const simulateMergeL0 = async () => {
        if (layersWithSelections.length !== 1) {
            setSimulatedL0(null);
            setSimulatedJacc(null);
            return;
        }

        const layer = layersWithSelections[0];
        const tokenIndices = selectedTokensForCombining
            .filter((t) => t.layer === layer)
            .map((t) => t.tokenIdx);

        if (tokenIndices.length === 0) {
            setSimulatedL0(null);
            setSimulatedJacc(null);
            return;
        }

        setSimulating(true);
        try {
            const response = await api.simulateMerge(promptId, layer, tokenIndices);
            setSimulatedL0(response.l0);
            setSimulatedJacc(response.jacc);
        } catch (error) {
            console.error("Failed to simulate merge:", error);
            setSimulatedL0(null);
            setSimulatedJacc(null);
        } finally {
            setSimulating(false);
        }
    };

    const combineMasks = async () => {
        if (combining || layersWithSelections.length !== 1) return;

        const layer = layersWithSelections[0];
        const tokenIndices = selectedTokensForCombining
            .filter((t) => t.layer === layer)
            .map((t) => t.tokenIdx);

        setCombining(true);
        try {
            await api.combineMasks(promptId, layer, tokenIndices, description);
            setSelectedTokensForCombining([]);
            setMultiSelectMode(false);
            setDescription("");
            setSimulatedL0(null);
            setSimulatedJacc(null);
            onMaskCreated();
        } catch (error) {
            console.error("Failed to combine masks:", error);
        } finally {
            setCombining(false);
        }
    };

    return (
        <div className="p-3 border border-gray-300 rounded-lg mb-4 bg-white">
            <div className="flex gap-2 items-center flex-wrap">
                <button
                    className={`px-4 py-2 border-2 rounded font-bold transition-all ${
                        multiSelectMode
                            ? "bg-blue-500 text-white border-blue-500"
                            : "bg-white text-blue-500 border-blue-500 hover:bg-blue-50"
                    }`}
                    onClick={toggleMultiSelectMode}
                >
                    {multiSelectMode ? "✓ Multi-Select Mode" : "Enable Multi-Select"}
                </button>
                <input
                    type="text"
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    placeholder="Description"
                    className="px-3 py-2 border border-gray-300 rounded"
                />

                {multiSelectMode && selectedTokensForCombining.length > 0 && (
                    <>
                        <button
                            className="px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600"
                            onClick={clearSelections}
                        >
                            Clear ({selectedTokensForCombining.length})
                        </button>

                        {simulatedL0 !== null && (
                            <span className="px-4 py-2 bg-blue-100 border border-blue-500 rounded text-blue-700 font-bold text-sm">
                                L0: {simulating ? "..." : simulatedL0}
                            </span>
                        )}

                        {simulatedJacc !== null && (
                            <span className="px-4 py-2 bg-blue-100 border border-blue-500 rounded text-blue-700 font-bold text-sm">
                                Jacc: {simulating ? "..." : simulatedJacc.toFixed(3)}
                            </span>
                        )}

                        <button
                            className={`px-4 py-2 rounded font-bold ${
                                layersWithSelections.length !== 1 || combining
                                    ? "bg-gray-300 cursor-not-allowed"
                                    : "bg-green-500 text-white hover:bg-green-600"
                            }`}
                            disabled={layersWithSelections.length !== 1 || combining}
                            onClick={combineMasks}
                        >
                            {combining ? "Combining..." : "Combine Masks"}
                        </button>

                        {layersWithSelections.length > 1 && (
                            <div className="flex items-start gap-2 p-3 bg-yellow-50 border border-yellow-200 border-l-4 border-l-orange-500 rounded-md text-yellow-900 max-w-md">
                                <span className="text-xl mt-0.5">⚠️</span>
                                <span className="text-sm leading-relaxed font-medium">
                                    Multi-select only available on a single layer. Please clear selections and select from one layer only.
                                </span>
                            </div>
                        )}
                    </>
                )}
            </div>
        </div>
    );
}

// spd/app/frontend/src/lib/components/MaskCombinePanel.svelte
<script lang="ts">
    import { multiSelectMode, selectedTokensForCombining } from "$lib/stores/componentState";
    import { api } from "$lib/api";
    import { createEventDispatcher } from "svelte";

    const dispatch = createEventDispatcher();

    export let promptId: string;

    let combining = false;
    let description = "";
    let simulatedL0: number | null = null;
    let simulatedJacc: number | null = null;
    let simulating = false;

    function toggleMultiSelectMode() {
        $multiSelectMode = !$multiSelectMode;
        if (!$multiSelectMode) clearSelections();
    }

    function clearSelections() {
        $selectedTokensForCombining = [];
        simulatedL0 = null;
        simulatedJacc = null;
    }

    // Reactively simulate merge whenever selections change
    $: if ($selectedTokensForCombining.length > 0 && layersWithSelections.length === 1) {
        simulateMergeL0();
    } else {
        simulatedL0 = null;
        simulatedJacc = null;
    }

    async function simulateMergeL0() {
        if (layersWithSelections.length !== 1) {
            simulatedL0 = null;
            simulatedJacc = null;
            return;
        }

        const layer = layersWithSelections[0];
        const tokenIndices = $selectedTokensForCombining
            .filter((t) => t.layer === layer)
            .map((t) => t.tokenIdx);

        if (tokenIndices.length === 0) {
            simulatedL0 = null;
            simulatedJacc = null;
            return;
        }

        simulating = true;
        try {
            const response = await api.simulateMerge(promptId, layer, tokenIndices);
            simulatedL0 = response.l0;
            simulatedJacc = response.jacc;
        } catch (error) {
            console.error("Failed to simulate merge:", error);
            simulatedL0 = null;
            simulatedJacc = null;
        } finally {
            simulating = false;
        }
    }

    // Make this reactive
    $: layersWithSelections = (() => {
        const layers = new Set<string>();
        $selectedTokensForCombining.forEach((token) => layers.add(token.layer));
        return Array.from(layers);
    })();

    async function combineMasks() {
        if (combining) return;

        if (layersWithSelections.length !== 1) return;

        const layer = layersWithSelections[0];
        const tokenIndices = $selectedTokensForCombining
            .filter((t) => t.layer === layer)
            .map((t) => t.tokenIdx);

        combining = true;
        try {
            await api.combineMasks(promptId, layer, tokenIndices, description);

            // Clear selections after successful combination
            $selectedTokensForCombining = [];
            $multiSelectMode = false;
            description = ""; // Reset description
            simulatedL0 = null; // Reset simulated L0
            simulatedJacc = null;

            // Notify parent to refresh saved masks
            dispatch('maskCreated');
        } catch (error) {
            console.error("Failed to combine masks:", error);
        } finally {
            combining = false;
        }
    }
</script>

<div class="mask-combine-panel">
    <div class="controls">
        <button
            class="mode-toggle"
            class:active={$multiSelectMode}
            on:click={toggleMultiSelectMode}
        >
            {$multiSelectMode ? "✓ Multi-Select Mode" : "Enable Multi-Select"}
        </button>
        <input type="text" bind:value={description} placeholder="Description" />

        {#if $multiSelectMode && $selectedTokensForCombining.length > 0}
            <button class="clear-btn" on:click={clearSelections}>
                Clear ({$selectedTokensForCombining.length})
            </button>

            {#if simulatedL0 !== null}
                <span class="metric-display">
                    L0: {simulating ? "..." : simulatedL0}
                </span>
            {/if}

            {#if simulatedJacc !== null}
                <span class="metric-display">
                    Jacc: {simulating ? "..." : simulatedJacc}
                </span>
            {/if}

            <button
                class="combine-btn"
                disabled={layersWithSelections.length !== 1 || combining}
                on:click={combineMasks}
            >
                {combining ? "Combining..." : "Combine Masks"}
            </button>

            {#if layersWithSelections.length > 1}
                <div class="multi-layer-warning">
                    <span class="warning-icon">⚠️</span>
                    <span class="warning-text">
                        Multi-select only available on a single layer.
                        Please clear selections and select from one layer only.
                    </span>
                </div>
            {/if}
        {/if}
    </div>
</div>

<style>
    .mask-combine-panel {
        padding: 0.75rem;
        border: 1px solid #ddd;
        border-radius: 8px;
        margin-bottom: 1rem;
        background: white;
    }

    .controls {
        display: flex;
        gap: 0.5rem;
        align-items: center;
    }

    .mode-toggle {
        padding: 0.5rem 1rem;
        border: 2px solid #007bff;
        background: white;
        color: #007bff;
        border-radius: 4px;
        cursor: pointer;
        font-weight: bold;
        transition: all 0.2s;
    }

    .mode-toggle:hover {
        background: #f0f8ff;
    }

    .mode-toggle.active {
        background: #007bff;
        color: white;
    }

    .clear-btn {
        padding: 0.5rem 1rem;
        background: #f44336;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    .clear-btn:hover {
        background: #d32f2f;
    }

    .combine-btn {
        padding: 0.5rem 1rem;
        background: #4caf50;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-weight: bold;
    }

    .combine-btn:hover:not(:disabled) {
        background: #45a049;
    }

    .combine-btn:disabled {
        background: #ccc;
        cursor: not-allowed;
    }

    .warning {
        padding: 0.25rem 0.5rem;
        color: #856404;
        font-size: 0.85rem;
    }

    .multi-layer-warning {
        display: flex;
        align-items: flex-start;
        gap: 0.5rem;
        padding: 0.75rem;
        background: #fff3cd;
        border: 1px solid #ffeaa7;
        border-left: 4px solid #ff6b35;
        border-radius: 6px;
        color: #664d03;
        max-width: 400px;
        margin: 0.5rem 0;
    }

    .warning-icon {
        font-size: 1.2rem;
        margin-top: 0.1rem;
    }

    .warning-text {
        font-size: 0.9rem;
        line-height: 1.4;
        font-weight: 500;
    }

    .metric-display {
        padding: 0.5rem 1rem;
        background: #e3f2fd;
        border: 1px solid #2196f3;
        border-radius: 4px;
        color: #1976d2;
        font-weight: bold;
        font-size: 0.9rem;
    }
</style>
