// spd/app/frontend-react/components/TokenPredictions.tsx
"use client";

import { useRef, useEffect } from "react";
import type { OutputTokenLogit, ComponentMask } from "@/lib/api";

interface TokenPredictionsProps {
    tokenLogits: OutputTokenLogit[][];
    promptTokens: string[];
    containerClass?: string;
    appliedMask?: ComponentMask | null;
}

let isScrolling = false;

export default function TokenPredictions({
    tokenLogits,
    promptTokens,
    containerClass = "",
    appliedMask = null
}: TokenPredictionsProps) {
    const containerRef = useRef<HTMLDivElement>(null);

    const hasAblation = (tokenIdx: number): boolean => {
        if (!appliedMask) return false;
        return Object.values(appliedMask).some(
            (tokenMasks) => tokenMasks[tokenIdx] && tokenMasks[tokenIdx].length > 0
        );
    };

    const getProbabilityColor = (probability: number): string => {
        const p = Math.max(0, Math.min(1, probability));
        const whiteAmount = Math.round(255 - (255 - 100) * p);
        return `rgb(${whiteAmount}, ${whiteAmount}, 255)`;
    };

    const syncScroll = (event: Event) => {
        if (isScrolling) return;

        const target = event.target as HTMLElement;
        const scrollLeft = target.scrollLeft;

        isScrolling = true;

        const containers = document.querySelectorAll(".logits-display-container");
        for (const container of containers) {
            if (container !== target) {
                (container as HTMLElement).scrollLeft = scrollLeft;
            }
        }

        setTimeout(() => {
            isScrolling = false;
        }, 10);
    };

    useEffect(() => {
        const container = containerRef.current;
        if (container) {
            container.addEventListener("scroll", syncScroll);
            return () => container.removeEventListener("scroll", syncScroll);
        }
    }, []);

    return (
        <div
            ref={containerRef}
            className={`logits-display-container overflow-x-auto border border-gray-300 rounded-md bg-white ${containerClass} [scrollbar-width:none] [&::-webkit-scrollbar]:hidden`}
        >
            <div className="flex flex-row flex-nowrap gap-0 min-w-fit p-2 w-max overflow-visible">
                {tokenLogits.map((tokenPredictions, tokenIdx) => (
                    <div
                        key={tokenIdx}
                        className={`bg-white rounded-md border w-[140px] p-1 mr-1 ${
                            hasAblation(tokenIdx)
                                ? "border-2 border-orange-500 bg-orange-50"
                                : "border-gray-300"
                        }`}
                    >
                        <div className="text-gray-800 text-center relative">
                            <div className="text-xs font-mono mt-1 break-all">
                                &quot;{promptTokens[tokenIdx]}&quot;
                            </div>
                        </div>
                        <div className="flex flex-col gap-0.5">
                            {tokenPredictions.map((prediction, idx) => (
                                <div
                                    key={idx}
                                    className="flex flex-row justify-between items-center rounded-sm text-xs px-1 py-0.5 my-0.5"
                                    style={{ backgroundColor: getProbabilityColor(prediction.probability) }}
                                >
                                    <span className="font-mono text-xs text-gray-800 overflow-hidden whitespace-nowrap text-ellipsis text-left flex-1 mr-1 px-1 py-0.5 rounded-sm">
                                        &quot;{prediction.token}&quot;
                                    </span>
                                    <span className="font-mono text-[0.65rem] text-right flex-shrink-0">
                                        {prediction.probability.toFixed(3)}
                                    </span>
                                </div>
                            ))}
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}

// spd/app/frontend/src/lib/components/TokenPredictions.svelte
<script lang="ts">
    import type { OutputTokenLogit, ComponentMask } from "$lib/api";
    import { isScrolling } from "$lib/stores/componentState";

    export let tokenLogits: OutputTokenLogit[][];
    export let promptTokens: string[];
    export let containerClass: string = "";
    export let appliedMask: ComponentMask | null = null;

    function hasAblation(tokenIdx: number): boolean {
        if (!appliedMask) return false;
        return Object.values(appliedMask).some(
            tokenMasks => tokenMasks[tokenIdx] && tokenMasks[tokenIdx].length > 0
        );
    }

    function getProbabilityColor(probability: number): string {
        // Clamp probability between 0 and 1
        const p = Math.max(0, Math.min(1, probability));
        // Linear interpolation from white (255) to medium blue (100)
        const whiteAmount = Math.round(255 - (255 - 100) * p);
        return `rgb(${whiteAmount}, ${whiteAmount}, 255)`;
    }

    function syncScroll(event: Event) {
        if ($isScrolling) return;

        const target = event.target as HTMLElement;
        const scrollLeft = target.scrollLeft;

        $isScrolling = true;

        const containers = document.querySelectorAll(".logits-display-container");
        for (const container of containers) {
            if (container !== target) {
                (container as HTMLElement).scrollLeft = scrollLeft;
            }
        }

        setTimeout(() => {
            $isScrolling = false;
        }, 10);
    }
</script>

<div class="logits-display-container {containerClass}" on:scroll={syncScroll}>
    <div class="logits-display">
        {#each tokenLogits as tokenPredictions, tokenIdx}
            <div class="token-predictions" class:has-ablation={hasAblation(tokenIdx)}>
                <div class="token-header">
                    <div class="token-name">
                        "{promptTokens[tokenIdx]}"
                    </div>
                </div>
                <div class="predictions-list">
                    {#each tokenPredictions as prediction}
                        <div
                            class="prediction-item"
                            style="background-color: {getProbabilityColor(prediction.probability)}"
                        >
                            <span class="prediction-token">"{prediction.token}"</span>
                            <span class="prediction-prob">{prediction.probability.toFixed(3)}</span>
                        </div>
                    {/each}
                </div>
            </div>
        {/each}
    </div>
</div>

<style>
    .logits-display-container {
        overflow-x: auto;
        margin-bottom: 0;
        border: 1px solid #ddd;
        border-radius: 6px;
        background: white;
        scrollbar-width: none;
    }

    .logits-display-container::-webkit-scrollbar {
        display: none;
    }

    .logits-display-container.original {
        border-color: #4caf50;
    }

    .logits-display {
        display: flex !important;
        flex-direction: row !important;
        flex-wrap: nowrap !important;
        gap: 0;
        min-width: fit-content;
        padding: 0.5rem;
        width: max-content;
        overflow: visible;
    }

    .token-predictions {
        background: white;
        border-radius: 6px;
        border: 1px solid #ddd;
        width: 140px;
        padding: 0.25rem;
        margin-right: 0.25rem;
    }

    .token-header {
        color: #333;
        text-align: center;
        position: relative;
    }

    .token-predictions.has-ablation {
        border-color: #ff6b35;
        border-width: 2px;
        background: #fff8f5;
    }

    .ablation-indicator {
        position: absolute;
        top: -8px;
        right: -8px;
        font-size: 0.6rem;
        background: white;
        border-radius: 50%;
        padding: 2px;
    }

    .token-name {
        font-size: 0.8rem;
        color: #333;
        font-family: monospace;
        margin-top: 0.2rem;
        word-break: break-all;
    }

    .predictions-list {
        display: flex;
        flex-direction: column;
        gap: 0.1rem;
    }

    .prediction-item {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        align-items: center;
        border-radius: 2px;
        font-size: 0.7rem;
        padding: 0.1rem 0.2rem;
        margin: 0.05rem 0;
    }

    .prediction-token {
        font-family: monospace;
        font-size: 0.7rem;
        color: #333;
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
        text-align: left;
        flex: 1;
        margin-right: 0.2rem;
        padding: 0.1rem 0.3rem;
        border-radius: 2px;
    }

    .prediction-prob {
        font-family: monospace;
        font-size: 0.65rem;
        text-align: right;
        flex-shrink: 0;
    }
</style>
