// spd/app/frontend/src/lib/components/OriginalPredictions.svelte
<script lang="ts">
    import TokenPredictions from "./TokenPredictions.svelte";
    import type { OutputTokenLogit } from "$lib/api";

    export let tokenLogits: OutputTokenLogit[][];
    export let promptTokens: string[];
    export let title: string;
</script>

<div class="predictions-section">
    <h2>{@html title}</h2>
    <TokenPredictions
        {tokenLogits}
        {promptTokens}
        containerClass="original"
    />
</div>

<style>
    .predictions-section {
        padding: 1rem;
        border: 2px solid #4caf50;
        border-radius: 8px;
        background-color: #f8fff8;
        margin-bottom: 1rem;
    }

    .predictions-section h2 {
        margin: 0 0 0.5rem 0;
        color: #2e7d2e;
    }
</style>

// spd/app/frontend-react/components/OriginalPredictions.tsx
"use client";

import type { OutputTokenLogit } from "@/lib/api";
import TokenPredictions from "./TokenPredictions";

interface OriginalPredictionsProps {
    tokenLogits: OutputTokenLogit[][];
    promptTokens: string[];
    title: string;
}

export default function OriginalPredictions({ tokenLogits, promptTokens, title }: OriginalPredictionsProps) {
    return (
        <div className="mb-6">
            <h3
                className="text-lg font-semibold mb-2 text-gray-800"
                dangerouslySetInnerHTML={{ __html: title }}
            />
            <TokenPredictions
                tokenLogits={tokenLogits}
                promptTokens={promptTokens}
                containerClass="original border-green-500"
            />
        </div>
    );
}
