// spd/app/frontend/src/lib/components/RunSelector.svelte
<script lang="ts">
    import { api } from "$lib/api";

    export let wandbRunId: string | null = null;
    export let loadingRun: boolean = false;
    export let isLoading: boolean = false;

    const presetRuns = [
        { id: "ry05f67a", label: "Run ry05f67a" },
        { id: "6a7en259", label: "Run 6a7en259" }
    ];

    async function loadRun() {
        if (!wandbRunId?.trim()) return;

        loadingRun = true;
        try {
            await api.loadRun(wandbRunId);
        } catch (error: any) {
            console.error(`Error loading run: ${error.message}`);
            alert(`Failed to load run: ${error.message}`);
        }
        loadingRun = false;
    }
</script>

<div class="run-selector">
    <label for="wandb-run-id">W&B Run ID</label>
    <div class="input-group">
        <input
            type="text"
            id="wandb-run-id"
            list="run-options"
            bind:value={wandbRunId}
            disabled={loadingRun || isLoading}
            placeholder="Select or enter run ID"
        />
        <datalist id="run-options">
            {#each presetRuns as preset}
                <option value={preset.id}>{preset.label}</option>
            {/each}
        </datalist>
        <button
            on:click={loadRun}
            disabled={loadingRun || isLoading || !wandbRunId?.trim()}
        >
            {loadingRun ? "Loading..." : "Load Run"}
        </button>
    </div>
</div>

<style>
    .run-selector {
        margin-bottom: 1rem;
    }

    .run-selector label {
        display: block;
        margin-bottom: 0.5rem;
        font-weight: 600;
        color: #333;
        font-size: 0.9rem;
    }

    .input-group {
        display: flex;
        gap: 0.5rem;
    }

    .input-group input[type="text"] {
        flex: 1;
        padding: 0.5rem;
        border: 1px solid #ddd;
        border-radius: 4px;
        font-size: 1rem;
    }

    .input-group input[type="text"]:focus {
        outline: none;
        border-color: #4a90e2;
        box-shadow: 0 0 0 2px rgba(74, 144, 226, 0.1);
    }

    .input-group button {
        padding: 0.5rem 1rem;
        background-color: #4a90e2;
        color: white;
        border: none;
        border-radius: 4px;
        font-size: 1rem;
        cursor: pointer;
        white-space: nowrap;
    }

    .input-group button:hover:not(:disabled) {
        background-color: #357abd;
    }

    .input-group button:disabled {
        background-color: #ccc;
        cursor: not-allowed;
    }
</style>

// spd/app/frontend-react/components/RunSelector.tsx
"use client";

import { useState } from "react";
import { api } from "@/lib/api";

interface RunSelectorProps {
    wandbRunId: string | null;
    setWandbRunId: (id: string) => void;
    loadingRun: boolean;
    setLoadingRun: (loading: boolean) => void;
    isLoading: boolean;
}

const presetRuns = [
    { id: "ry05f67a", label: "Run ry05f67a" },
    { id: "6a7en259", label: "Run 6a7en259" }
];

export default function RunSelector({
    wandbRunId,
    setWandbRunId,
    loadingRun,
    setLoadingRun,
    isLoading
}: RunSelectorProps) {
    const loadRun = async () => {
        if (!wandbRunId?.trim()) return;

        setLoadingRun(true);
        try {
            await api.loadRun(wandbRunId);
        } catch (error: any) {
            console.error(`Error loading run: ${error.message}`);
            alert(`Failed to load run: ${error.message}`);
        }
        setLoadingRun(false);
    };

    return (
        <div className="mb-4">
            <label htmlFor="wandb-run-id" className="block mb-2 font-semibold text-gray-800 text-sm">
                W&B Run ID
            </label>
            <div className="flex gap-2">
                <input
                    type="text"
                    id="wandb-run-id"
                    list="run-options"
                    value={wandbRunId || ""}
                    onChange={(e) => setWandbRunId(e.target.value)}
                    disabled={loadingRun || isLoading}
                    placeholder="Select or enter run ID"
                    className="flex-1 px-4 py-2 border border-gray-300 rounded text-base focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"
                />
                <datalist id="run-options">
                    {presetRuns.map((preset) => (
                        <option key={preset.id} value={preset.id}>
                            {preset.label}
                        </option>
                    ))}
                </datalist>
                <button
                    onClick={loadRun}
                    disabled={loadingRun || isLoading || !wandbRunId?.trim()}
                    className={`px-4 py-2 rounded text-base whitespace-nowrap ${
                        loadingRun || isLoading || !wandbRunId?.trim()
                            ? "bg-gray-300 cursor-not-allowed"
                            : "bg-blue-500 text-white hover:bg-blue-600"
                    }`}
                >
                    {loadingRun ? "Loading..." : "Load Run"}
                </button>
            </div>
        </div>
    );
}
