// spd/app/frontend/src/lib/components/SavedMasksPanel.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { api } from "$lib/api";
    import type { MaskOverrideDTO } from "$lib/api";

    export let onApplyMask: (maskId: string) => void;

    let savedMasks: MaskOverrideDTO[] = [];
    let loading = false;

    export async function loadMasks() {
        loading = true;
        try {
            savedMasks = await api.getMaskOverrides();
        } catch (error) {
            console.error("Failed to load mask overrides:", error);
        } finally {
            loading = false;
        }
    }

    function handleApply(maskId: string) {
        onApplyMask(maskId);
    }

    onMount(() => {
        loadMasks();
    });
</script>

<div class="saved-masks-panel">
    <div class="panel-header">
        <h3>Saved Masks</h3>
        <button class="refresh-btn" on:click={loadMasks} disabled={loading}>
            {loading ? "Loading..." : "Refresh"}
        </button>
    </div>

    {#if savedMasks.length === 0}
        <div class="empty-state">
            No saved masks yet. Create masks using multi-select mode below.
        </div>
    {:else}
        <div class="masks-container">
            {#each savedMasks as mask}
                <div class="mask-card">
                    <div class="mask-info">
                        <div class="mask-description">
                            {mask.description || "Unnamed mask"}
                        </div>
                        <div class="mask-details">
                            <span class="mask-layer">Layer: {mask.layer}</span>
                            <span class="mask-l0">L0: {mask.combined_mask.l0}</span>
                        </div>
                    </div>
                    <button
                        class="apply-btn"
                        on:click={() => handleApply(mask.id)}
                    >
                        Apply as Ablation
                    </button>
                </div>
            {/each}
        </div>
    {/if}
</div>

<style>
    .saved-masks-panel {
        margin-bottom: 1rem;
        padding: 1rem;
        background: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: 8px;
    }

    .panel-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 1rem;
    }

    .panel-header h3 {
        margin: 0;
        font-size: 1.1rem;
        color: #333;
    }

    .refresh-btn {
        padding: 0.25rem 0.75rem;
        background: #007bff;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 0.85rem;
    }

    .refresh-btn:hover:not(:disabled) {
        background: #0056b3;
    }

    .refresh-btn:disabled {
        background: #ccc;
        cursor: not-allowed;
    }

    .empty-state {
        padding: 2rem;
        text-align: center;
        color: #6c757d;
        font-style: italic;
    }

    .masks-container {
        display: flex;
        gap: 0.75rem;
        overflow-x: auto;
        padding-bottom: 0.5rem;
    }

    .mask-card {
        flex: 0 0 auto;
        min-width: 200px;
        padding: 0.75rem;
        background: white;
        border: 2px solid #e9ecef;
        border-radius: 6px;
        transition: all 0.2s;
    }

    .mask-card:hover {
        border-color: #007bff;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }

    .mask-info {
        margin-bottom: 0.75rem;
    }

    .mask-description {
        font-weight: 500;
        color: #333;
        margin-bottom: 0.5rem;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    .mask-details {
        display: flex;
        flex-direction: column;
        gap: 0.25rem;
        font-size: 0.85rem;
        color: #6c757d;
    }

    .mask-layer {
        font-weight: 500;
    }

    .mask-l0 {
        color: #007bff;
    }

    .apply-btn {
        width: 100%;
        padding: 0.5rem;
        background: #007bff;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-weight: 500;
        transition: background 0.2s;
    }

    .apply-btn:hover {
        background: #0056b3;
    }

    /* Scrollbar styling */
    .masks-container::-webkit-scrollbar {
        height: 6px;
    }

    .masks-container::-webkit-scrollbar-track {
        background: #f1f1f1;
        border-radius: 3px;
    }

    .masks-container::-webkit-scrollbar-thumb {
        background: #888;
        border-radius: 3px;
    }

    .masks-container::-webkit-scrollbar-thumb:hover {
        background: #555;
    }
</style>

// spd/app/frontend-react/components/SavedMasksPanel.tsx
"use client";

import { useState, useEffect, forwardRef, useImperativeHandle } from "react";
import { api } from "@/lib/api";
import type { MaskOverrideDTO } from "@/lib/api";

interface SavedMasksPanelProps {
    onApplyMask: (maskId: string) => void;
}

export interface SavedMasksPanelRef {
    loadMasks: () => Promise<void>;
}

const SavedMasksPanel = forwardRef<SavedMasksPanelRef, SavedMasksPanelProps>(
    ({ onApplyMask }, ref) => {
        const [savedMasks, setSavedMasks] = useState<MaskOverrideDTO[]>([]);
        const [loading, setLoading] = useState(false);

        const loadMasks = async () => {
            setLoading(true);
            try {
                const masks = await api.getMaskOverrides();
                setSavedMasks(masks);
            } catch (error) {
                console.error("Failed to load mask overrides:", error);
            } finally {
                setLoading(false);
            }
        };

        useImperativeHandle(ref, () => ({
            loadMasks
        }));

        useEffect(() => {
            loadMasks();
        }, []);

        return (
            <div className="mb-4 p-4 bg-gray-50 border border-gray-300 rounded-lg">
                <div className="flex justify-between items-center mb-4">
                    <h3 className="m-0 text-lg text-gray-800">Saved Masks</h3>
                    <button
                        className={`px-3 py-1 text-white rounded text-sm ${
                            loading ? "bg-gray-400 cursor-not-allowed" : "bg-blue-500 hover:bg-blue-600"
                        }`}
                        onClick={loadMasks}
                        disabled={loading}
                    >
                        {loading ? "Loading..." : "Refresh"}
                    </button>
                </div>

                {savedMasks.length === 0 ? (
                    <div className="py-8 text-center text-gray-500 italic">
                        No saved masks yet. Create masks using multi-select mode below.
                    </div>
                ) : (
                    <div className="flex gap-3 overflow-x-auto pb-2">
                        {savedMasks.map((mask) => (
                            <div
                                key={mask.id}
                                className="flex-[0_0_auto] min-w-[200px] p-3 bg-white border-2 border-gray-200 rounded-md transition-all hover:border-blue-500 hover:shadow-md"
                            >
                                <div className="mb-3">
                                    <div className="font-medium text-gray-800 mb-2 overflow-hidden text-ellipsis whitespace-nowrap">
                                        {mask.description || "Unnamed mask"}
                                    </div>
                                    <div className="flex flex-col gap-1 text-sm text-gray-600">
                                        <span className="font-medium">Layer: {mask.layer}</span>
                                        <span className="text-blue-500">L0: {mask.combined_mask.l0}</span>
                                    </div>
                                </div>
                                <button
                                    className="w-full px-4 py-2 bg-blue-500 text-white rounded font-medium transition-colors hover:bg-blue-600"
                                    onClick={() => onApplyMask(mask.id)}
                                >
                                    Apply as Ablation
                                </button>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        );
    }
);

SavedMasksPanel.displayName = "SavedMasksPanel";

export default SavedMasksPanel;
