// spd/app/frontend-client/src/App.svelte
<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<script lang="ts">
    import { onMount } from "svelte";
    import { api } from "./lib/api";
    import type { RunPromptResponse, ComponentMask, Status, SparseVector } from "./lib/api";
    import {
        runAblation,
        popupData,
        ablationResults,
        promptWorkspaces,
        currentWorkspaceIndex,
        type PromptWorkspace
    } from "./lib/stores/componentState";

    import RunSelector from "./lib/components/RunSelector.svelte";
    import ComponentHeatmap from "./lib/components/ComponentHeatmap.svelte";
    import DisabledComponentsPanel from "./lib/components/DisabledComponentsPanel.svelte";
    import ComponentDetailModal from "./lib/components/ComponentDetailModal.svelte";
    import OriginalPredictions from "./lib/components/OriginalPredictions.svelte";
    import AblationPredictions from "./lib/components/AblationPredictions.svelte";
    import SavedMasksPanel from "./lib/components/SavedMasksPanel.svelte";
    import ActivationContextsTab from "./lib/components/ActivationContextsTab.svelte";

    let isLoading = false;
    let result: RunPromptResponse | null = null;
    let currentPromptId: string | null = null;
    let wandbRunId: string | null = null;
    let loadingRun = false;
    let savedMasksPanel: SavedMasksPanel;
    let availablePrompts: { index: number; text: string; full_text: string }[] = [];
    let showAvailablePrompts = false;
    let activeTab: "ablation" | "activation-contexts" = "ablation";

    async function loadAvailablePrompts() {
        try {
            availablePrompts = await api.getAvailablePrompts();
        } catch (error: any) {
            console.error("Failed to load prompts:", error.message);
        }
    }

    function toggleAvailablePrompts() {
        showAvailablePrompts = !showAvailablePrompts;
        if (showAvailablePrompts && availablePrompts.length === 0) {
            loadAvailablePrompts();
        }
    }

    // Helper functions for workspace management
    function createNewWorkspace(promptData: RunPromptResponse): PromptWorkspace {
        const newMask: ComponentMask = {};
        for (const layer of promptData.layer_cis) {
            newMask[layer.module] = promptData.prompt_tokens.map(() => []);
        }

        return {
            promptId: promptData.prompt_id,
            promptData,
            ablationResults: [],
            runAblation: newMask
        };
    }

    function switchToWorkspace(index: number) {
        if (index >= 0 && index < $promptWorkspaces.length) {
            $currentWorkspaceIndex = index;
            const workspace = $promptWorkspaces[index];
            result = workspace.promptData;
            currentPromptId = workspace.promptId;
            $runAblation = workspace.runAblation;
            $ablationResults = workspace.ablationResults;
        }
    }

    function updateCurrentWorkspace() {
        if (
            $currentWorkspaceIndex >= 0 &&
            $currentWorkspaceIndex < $promptWorkspaces.length &&
            result
        ) {
            $promptWorkspaces[$currentWorkspaceIndex] = {
                ...$promptWorkspaces[$currentWorkspaceIndex],
                runAblation: $runAblation,
                ablationResults: $ablationResults
            };
        }
    }

    function closeWorkspace(index: number) {
        $promptWorkspaces = $promptWorkspaces.filter((_, i) => i !== index);

        if ($promptWorkspaces.length === 0) {
            // No workspaces left
            result = null;
            currentPromptId = null;
            $currentWorkspaceIndex = 0;
        } else if (index <= $currentWorkspaceIndex) {
            // Adjust current index if necessary
            const newIndex = Math.max(0, $currentWorkspaceIndex - 1);
            $currentWorkspaceIndex = newIndex;
            switchToWorkspace(newIndex);
        }
    }

    async function runPromptByIndex(datasetIndex: number) {
        isLoading = true;
        try {
            const promptData = await api.runPromptByIndex(datasetIndex);
            const newWorkspace = createNewWorkspace(promptData);

            // Add new workspace and switch to it
            $promptWorkspaces = [...$promptWorkspaces, newWorkspace];
            $currentWorkspaceIndex = $promptWorkspaces.length - 1;
            switchToWorkspace($currentWorkspaceIndex);
        } catch (error: any) {
            console.error(`Error: ${error.message}`);
        }
        isLoading = false;
    }

    async function applyMaskAsAblation(maskId: string) {
        if (!result || !currentPromptId) return;

        isLoading = true;
        try {
            const maskResult = await api.applyMaskAsAblation(currentPromptId, maskId);

            // Get mask info for display
            const masks = await api.getMaskOverrides();
            const appliedMask = masks.find((m) => m.id === maskId);

            // Add as an ablation result with description
            $ablationResults = [
                ...$ablationResults,
                {
                    tokenLogits: maskResult.tokenLogits,
                    applied_mask: {}, // The mask was applied uniformly to all tokens
                    id: Date.now(),
                    maskOverride: appliedMask // Store mask info for display
                }
            ];
        } catch (error: any) {
            console.error(`Error: ${error.message}`);
        }
        isLoading = false;
    }

    // Refresh saved masks after creating a new one
    export function refreshSavedMasks() {
        if (savedMasksPanel) {
            savedMasksPanel.loadMasks();
        }
    }

    function initializeRunAblation() {
        if (!result) return;
        const newMask: ComponentMask = {};
        for (const layer of result.layer_cis) {
            newMask[layer.module] = result.prompt_tokens.map(() => []);
        }
        $runAblation = newMask;
    }

    function toggleComponentDisabled(layerName: string, tokenIdx: number, componentIdx: number) {
        if (!$runAblation[layerName]) {
            $runAblation[layerName] = result!.prompt_tokens.map(() => []);
        }

        const disabledComponents = $runAblation[layerName][tokenIdx];
        const existingIdx = disabledComponents.indexOf(componentIdx);

        if (existingIdx === -1) {
            disabledComponents.push(componentIdx);
        } else {
            disabledComponents.splice(existingIdx, 1);
        }

        $runAblation = { ...$runAblation };
    }

    function isComponentDisabled(
        layerName: string,
        tokenIdx: number,
        componentIdx: number
    ): boolean {
        return $runAblation[layerName][tokenIdx].includes(componentIdx);
    }

    async function sendAblation() {
        if (!result || !currentPromptId) return;

        isLoading = true;
        try {
            const data = await api.ablateComponents(currentPromptId, $runAblation);

            const deepCopyMask: ComponentMask = {};
            for (const [layerName, tokenArrays] of Object.entries($runAblation)) {
                deepCopyMask[layerName] = tokenArrays.map((tokenMask) => [...tokenMask]);
            }

            $ablationResults = [
                ...$ablationResults,
                {
                    tokenLogits: data.token_logits,
                    applied_mask: deepCopyMask,
                    id: Date.now()
                }
            ];
        } catch (error: any) {
            console.error(`Error: ${error.message}`);
        }
        isLoading = false;
    }

    function openPopup(
        token: string,
        tokenIdx: number,
        layer: string,
        layerIdx: number,
        tokenCis: SparseVector
    ) {
        $popupData = { token, tokenIdx, layer, layerIdx, tokenCis };
    }

    function closePopup() {
        $popupData = null;
    }

    $: if (result) {
        initializeRunAblation();
    }

    let status: Status | null = null;
    async function getStatus() {
        console.log("getting status");
        status = await api.getStatus();
        console.log("status", status);
    }

    $: wandbRunId = status?.run_id ?? null;

    onMount(() => {
        getStatus();
        loadAvailablePrompts();
    });
</script>

<main>
    <div class="container">
        <!-- Top-level controls -->
        <div class="top-controls">
            <RunSelector bind:loadingRun bind:wandbRunId {isLoading} />

            <!-- Workspace Navigation -->
            <div class="workspace-navigation">
                <div class="workspace-header">
                    <h3>Prompt Workspaces</h3>
                    <button class="add-prompt-btn" on:click={toggleAvailablePrompts}>
                        {showAvailablePrompts ? "Cancel" : "+ Add Prompt"}
                    </button>
                </div>

                {#if showAvailablePrompts}
                    <div class="available-prompts-dropdown">
                        {#if availablePrompts.length === 0}
                            <p>Loading prompts...</p>
                        {:else}
                            <div class="prompt-list">
                                {#each availablePrompts as prompt, i}
                                    <button
                                        class="prompt-button"
                                        on:click={() => {
                                            runPromptByIndex(prompt.index);
                                            showAvailablePrompts = false;
                                        }}
                                        disabled={isLoading}
                                    >
                                        <span class="prompt-number">#{i + 1}</span>
                                        <span class="prompt-text">{prompt.text}</span>
                                    </button>
                                {/each}
                            </div>
                        {/if}
                    </div>
                {/if}

                {#if $promptWorkspaces.length > 0}
                    <div class="workspace-list">
                        {#each $promptWorkspaces as workspace, i}
                            <button
                                class="workspace-item"
                                class:active={i === $currentWorkspaceIndex}
                                on:click={() => switchToWorkspace(i)}
                            >
                                <span class="workspace-number">#{i + 1}</span>
                                <span class="workspace-text">
                                    {workspace.promptData.prompt_tokens.slice(0, 8).join(" ")}...
                                </span>
                                <span
                                    class="workspace-close"
                                    on:click|stopPropagation={() => closeWorkspace(i)}>×</span
                                >
                            </button>
                        {/each}
                    </div>
                {:else}
                    <div class="empty-workspaces">
                        No prompts loaded. Click "Add Prompt" to start.
                    </div>
                {/if}
            </div>

            <SavedMasksPanel bind:this={savedMasksPanel} onApplyMask={applyMaskAsAblation} />
        </div>

        <!-- Tab Navigation -->
        {#if result}
            <div class="tab-navigation">
                <button
                    class="tab-button"
                    class:active={activeTab === "ablation"}
                    on:click={() => (activeTab = "ablation")}
                >
                    Component Ablation
                </button>
                <button
                    class="tab-button"
                    class:active={activeTab === "activation-contexts"}
                    on:click={() => (activeTab = "activation-contexts")}
                >
                    Activation Contexts
                </button>
            </div>
        {/if}

        <div class="main-layout" class:hidden={activeTab !== "ablation"}>
            <!-- Left side: Static heatmap and controls -->
            <div class="left-panel">
                {#if result && currentPromptId}
                    <ComponentHeatmap
                        {result}
                        promptId={currentPromptId}
                        onCellClick={openPopup}
                        on:maskCreated={refreshSavedMasks}
                    />

                    <DisabledComponentsPanel
                        promptTokens={result.prompt_tokens}
                        {isLoading}
                        onSendAblation={sendAblation}
                        onToggleComponent={toggleComponentDisabled}
                    />
                {/if}
            </div>

            <!-- Right side: Scrollable predictions -->
            <div class="right-panel">
                {#if result && result.full_run_token_logits}
                    <OriginalPredictions
                        tokenLogits={result.full_run_token_logits}
                        promptTokens={result.prompt_tokens}
                        title="Original Model Predictions"
                    />
                {/if}

                {#if result && result.ci_masked_token_logits}
                    <OriginalPredictions
                        tokenLogits={result.ci_masked_token_logits}
                        promptTokens={result.prompt_tokens}
                        title="Original <strong>CI Masked</strong> Model Predictions"
                    />
                {/if}

                {#if result}
                    {#each $ablationResults as ablationResult}
                        <AblationPredictions
                            tokenLogits={ablationResult.tokenLogits}
                            promptTokens={result.prompt_tokens}
                            appliedMask={ablationResult.applied_mask}
                            maskOverride={ablationResult.maskOverride}
                        />
                    {/each}
                {/if}
            </div>
        </div>

        <!-- Activation Contexts Tab Content -->
        {#if activeTab === "activation-contexts"}
            <div class="activation-contexts-container">
                <ActivationContextsTab {result} />
            </div>
        {/if}

        <ComponentDetailModal
            onClose={closePopup}
            onToggleComponent={toggleComponentDisabled}
            {isComponentDisabled}
            promptId={currentPromptId}
        />
    </div>
</main>

<style>
    main {
        padding: 0.5rem;
        font-family:
            system-ui,
            -apple-system,
            sans-serif;
    }

    .container {
        max-width: none;
        margin: 0;
        display: flex;
        flex-direction: column;
        gap: 1rem;
    }

    .top-controls {
        display: flex;
        flex-direction: column;
        gap: 1rem;
        padding: 1rem;
        background: #f8f9fa;
        border-radius: 8px;
        border: 1px solid #dee2e6;
    }

    .main-layout {
        display: flex;
        gap: 1rem;
        min-height: 70vh;
    }

    .left-panel {
        padding: 0.5rem;
        flex: 0 0 50%;
        max-width: 50%;
        position: sticky;
        top: 1rem;
        align-self: flex-start;
        max-height: calc(100vh - 2rem);
        overflow-y: auto;
    }

    .right-panel {
        flex: 1;
        overflow-y: auto;
        padding-right: 1rem;
    }


    .prompt-list {
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
        max-height: 300px;
        overflow-y: auto;
    }

    .prompt-button {
        display: flex;
        align-items: flex-start;
        gap: 0.75rem;
        padding: 0.75rem;
        background: white;
        border: 2px solid #e9ecef;
        border-radius: 6px;
        cursor: pointer;
        text-align: left;
        transition: all 0.2s;
        font-family: inherit;
    }

    .prompt-button:hover:not(:disabled) {
        border-color: #007bff;
        background: #f0f8ff;
    }

    .prompt-button:disabled {
        opacity: 0.6;
        cursor: not-allowed;
    }

    .prompt-number {
        font-weight: bold;
        color: #666;
        min-width: 2rem;
        margin-top: 0.1rem;
    }

    .prompt-text {
        flex: 1;
        font-size: 0.9rem;
        line-height: 1.4;
        color: #333;
    }

    .workspace-navigation {
        margin-bottom: 1rem;
        padding: 1rem;
        background: #e8f4f8;
        border: 1px solid #b3d9e8;
        border-radius: 8px;
    }

    .workspace-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 1rem;
    }

    .workspace-header h3 {
        margin: 0;
        font-size: 1.1rem;
        color: #333;
    }

    .add-prompt-btn {
        padding: 0.5rem 1rem;
        background: #28a745;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-weight: 500;
        transition: background 0.2s;
    }

    .add-prompt-btn:hover {
        background: #218838;
    }

    .available-prompts-dropdown {
        margin-bottom: 1rem;
        padding: 1rem;
        background: white;
        border: 1px solid #dee2e6;
        border-radius: 6px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .workspace-list {
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
    }

    .workspace-item {
        display: flex;
        align-items: center;
        gap: 0.75rem;
        padding: 0.75rem;
        background: white;
        border: 2px solid #b3d9e8;
        border-radius: 6px;
        cursor: pointer;
        text-align: left;
        transition: all 0.2s;
        font-family: inherit;
    }

    .workspace-item:hover {
        background: #f0f8ff;
        border-color: #007bff;
    }

    .workspace-item.active {
        background: #007bff;
        color: white;
        border-color: #0056b3;
    }

    .workspace-number {
        font-weight: bold;
        min-width: 2rem;
        color: #666;
    }

    .workspace-item.active .workspace-number {
        color: white;
    }

    .workspace-text {
        flex: 1;
        font-size: 0.9rem;
        line-height: 1.4;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    .workspace-close {
        font-size: 1.2rem;
        font-weight: bold;
        cursor: pointer;
        padding: 0.1rem 0.3rem;
        border-radius: 50%;
        transition: background 0.2s;
        color: #666;
    }

    .workspace-item.active .workspace-close {
        color: white;
    }

    .workspace-close:hover {
        background: rgba(255, 0, 0, 0.1);
        color: red;
    }

    .workspace-item.active .workspace-close:hover {
        background: rgba(255, 255, 255, 0.2);
        color: white;
    }

    .empty-workspaces {
        padding: 2rem;
        text-align: center;
        color: #6c757d;
        font-style: italic;
    }

    .tab-navigation {
        display: flex;
        gap: 0.5rem;
        padding: 0 1rem;
        background: #f8f9fa;
        border-bottom: 2px solid #dee2e6;
    }

    .tab-button {
        padding: 0.75rem 1.5rem;
        background: transparent;
        border: none;
        border-bottom: 3px solid transparent;
        cursor: pointer;
        font-size: 1rem;
        font-weight: 500;
        color: #6c757d;
        transition: all 0.2s;
        position: relative;
        top: 2px;
    }

    .tab-button:hover {
        color: #007bff;
    }

    .tab-button.active {
        color: #007bff;
        border-bottom-color: #007bff;
        background: white;
    }

    .main-layout.hidden {
        display: none;
    }

    .activation-contexts-container {
        padding: 1rem;
        background: white;
        border-radius: 8px;
        min-height: 60vh;
    }
</style>

// spd/app/frontend-react/app/page.tsx
"use client";

import { useState, useEffect, useRef } from "react";
import { api } from "@/lib/api";
import type { RunPromptResponse, ComponentMask, StatusDTO } from "@/lib/api";
import { useComponentState, type PromptWorkspace, type AblationResult } from "@/lib/context/ComponentStateContext";
import RunSelector from "@/components/RunSelector";
import ComponentHeatmap from "@/components/ComponentHeatmap";
import DisabledComponentsPanel from "@/components/DisabledComponentsPanel";
import ComponentDetailModal from "@/components/ComponentDetailModal";
import OriginalPredictions from "@/components/OriginalPredictions";
import AblationPredictions from "@/components/AblationPredictions";
import SavedMasksPanel, { type SavedMasksPanelRef } from "@/components/SavedMasksPanel";

export default function Home() {
    const {
        runAblation,
        setRunAblation,
        setPopupData,
        ablationResults,
        setAblationResults,
        promptWorkspaces,
        setPromptWorkspaces,
        currentWorkspaceIndex,
        setCurrentWorkspaceIndex
    } = useComponentState();

    const [isLoading, setIsLoading] = useState(false);
    const [result, setResult] = useState<RunPromptResponse | null>(null);
    const [currentPromptId, setCurrentPromptId] = useState<string | null>(null);
    const [wandbRunId, setWandbRunId] = useState<string | null>(null);
    const [loadingRun, setLoadingRun] = useState(false);
    const [availablePrompts, setAvailablePrompts] = useState<{ index: number; text: string; full_text: string }[]>([]);
    const [showAvailablePrompts, setShowAvailablePrompts] = useState(false);
    const savedMasksPanelRef = useRef<SavedMasksPanelRef>(null);

    useEffect(() => {
        getStatus();
        loadAvailablePrompts();
    }, []);

    const getStatus = async () => {
        const status = await api.getStatus();
        setWandbRunId(status.run_id);
    };

    const loadAvailablePrompts = async () => {
        try {
            const prompts = await api.getAvailablePrompts();
            setAvailablePrompts(prompts);
        } catch (error: any) {
            console.error("Failed to load prompts:", error.message);
        }
    };

    const toggleAvailablePrompts = () => {
        setShowAvailablePrompts(!showAvailablePrompts);
        if (!showAvailablePrompts && availablePrompts.length === 0) {
            loadAvailablePrompts();
        }
    };

    const createNewWorkspace = (promptData: RunPromptResponse): PromptWorkspace => {
        const newMask: ComponentMask = {};
        for (const layer of promptData.layer_cis) {
            newMask[layer.module] = promptData.prompt_tokens.map(() => []);
        }

        return {
            promptId: promptData.prompt_id,
            promptData,
            ablationResults: [],
            runAblation: newMask
        };
    };

    const switchToWorkspace = (index: number) => {
        if (index >= 0 && index < promptWorkspaces.length) {
            setCurrentWorkspaceIndex(index);
            const workspace = promptWorkspaces[index];
            setResult(workspace.promptData);
            setCurrentPromptId(workspace.promptId);
            setRunAblation(workspace.runAblation);
            setAblationResults(workspace.ablationResults);
        }
    };

    const updateCurrentWorkspace = () => {
        if (currentWorkspaceIndex >= 0 && currentWorkspaceIndex < promptWorkspaces.length && result) {
            const updatedWorkspaces = [...promptWorkspaces];
            updatedWorkspaces[currentWorkspaceIndex] = {
                ...updatedWorkspaces[currentWorkspaceIndex],
                runAblation,
                ablationResults
            };
            setPromptWorkspaces(updatedWorkspaces);
        }
    };

    useEffect(() => {
        updateCurrentWorkspace();
    }, [runAblation, ablationResults]);

    const closeWorkspace = (index: number) => {
        const newWorkspaces = promptWorkspaces.filter((_, i) => i !== index);
        setPromptWorkspaces(newWorkspaces);

        if (newWorkspaces.length === 0) {
            setResult(null);
            setCurrentPromptId(null);
            setCurrentWorkspaceIndex(0);
        } else if (index <= currentWorkspaceIndex) {
            const newIndex = Math.max(0, currentWorkspaceIndex - 1);
            setCurrentWorkspaceIndex(newIndex);
            switchToWorkspace(newIndex);
        }
    };

    const runPromptByIndex = async (datasetIndex: number) => {
        setIsLoading(true);
        try {
            const promptData = await api.runPromptByIndex(datasetIndex);
            const newWorkspace = createNewWorkspace(promptData);

            setPromptWorkspaces([...promptWorkspaces, newWorkspace]);
            const newIndex = promptWorkspaces.length;
            setCurrentWorkspaceIndex(newIndex);
            switchToWorkspace(newIndex);
        } catch (error: any) {
            console.error(`Error: ${error.message}`);
        }
        setIsLoading(false);
    };

    const applyMaskAsAblation = async (maskId: string) => {
        if (!result || !currentPromptId) return;

        setIsLoading(true);
        try {
            const maskResult = await api.applyMaskAsAblation(currentPromptId, maskId);
            const masks = await api.getMaskOverrides();
            const appliedMask = masks.find((m) => m.id === maskId);

            setAblationResults([
                ...ablationResults,
                {
                    tokenLogits: maskResult.token_logits,
                    applied_mask: {},
                    id: Date.now(),
                    maskOverride: appliedMask
                }
            ]);
        } catch (error: any) {
            console.error(`Error: ${error.message}`);
        }
        setIsLoading(false);
    };

    const refreshSavedMasks = () => {
        if (savedMasksPanelRef.current) {
            savedMasksPanelRef.current.loadMasks();
        }
    };

    const initializeRunAblation = () => {
        if (!result) return;
        const newMask: ComponentMask = {};
        for (const layer of result.layer_cis) {
            newMask[layer.module] = result.prompt_tokens.map(() => []);
        }
        setRunAblation(newMask);
    };

    useEffect(() => {
        if (result) {
            initializeRunAblation();
        }
    }, [result]);

    const toggleComponentDisabled = (layerName: string, tokenIdx: number, componentIdx: number) => {
        if (!runAblation[layerName]) {
            runAblation[layerName] = result!.prompt_tokens.map(() => []);
        }

        const disabledComponents = runAblation[layerName][tokenIdx];
        const existingIdx = disabledComponents.indexOf(componentIdx);

        if (existingIdx === -1) {
            disabledComponents.push(componentIdx);
        } else {
            disabledComponents.splice(existingIdx, 1);
        }

        setRunAblation({ ...runAblation });
    };

    const isComponentDisabled = (layerName: string, tokenIdx: number, componentIdx: number): boolean => {
        return runAblation[layerName]?.[tokenIdx]?.includes(componentIdx) ?? false;
    };

    const sendAblation = async () => {
        if (!result || !currentPromptId) return;

        setIsLoading(true);
        try {
            const data = await api.ablateComponents(currentPromptId, runAblation);

            const deepCopyMask: ComponentMask = {};
            for (const [layerName, tokenArrays] of Object.entries(runAblation)) {
                deepCopyMask[layerName] = tokenArrays.map((tokenMask) => [...tokenMask]);
            }

            setAblationResults([
                ...ablationResults,
                {
                    tokenLogits: data.token_logits,
                    applied_mask: deepCopyMask,
                    id: Date.now()
                }
            ]);
        } catch (error: any) {
            console.error(`Error: ${error.message}`);
        }
        setIsLoading(false);
    };

    const openPopup = (token: string, tokenIdx: number, layer: string, layerIdx: number, tokenCis: any) => {
        setPopupData({ token, tokenIdx, layer, layerIdx, tokenCis });
    };

    const closePopup = () => {
        setPopupData(null);
    };

    return (
        <main className="p-2 font-sans">
            <div className="max-w-none m-0 flex flex-col gap-4">
                <div className="flex flex-col gap-4 p-4 bg-gray-50 rounded-lg border border-gray-300">
                    <RunSelector
                        wandbRunId={wandbRunId}
                        setWandbRunId={setWandbRunId}
                        loadingRun={loadingRun}
                        setLoadingRun={setLoadingRun}
                        isLoading={isLoading}
                    />

                    <div className="mb-4 p-4 bg-blue-50 border border-blue-300 rounded-lg">
                        <div className="flex justify-between items-center mb-4">
                            <h3 className="text-lg text-gray-800">Prompt Workspaces</h3>
                            <button
                                className="px-4 py-2 bg-green-500 text-white rounded font-medium hover:bg-green-600"
                                onClick={toggleAvailablePrompts}
                            >
                                {showAvailablePrompts ? "Cancel" : "+ Add Prompt"}
                            </button>
                        </div>

                        {showAvailablePrompts && (
                            <div className="mb-4 p-4 bg-white border border-gray-300 rounded-md shadow-md">
                                {availablePrompts.length === 0 ? (
                                    <p>Loading prompts...</p>
                                ) : (
                                    <div className="flex flex-col gap-2 max-h-[300px] overflow-y-auto">
                                        {availablePrompts.map((prompt, i) => (
                                            <button
                                                key={prompt.index}
                                                className="flex items-start gap-3 p-3 bg-white border-2 border-gray-200 rounded-md cursor-pointer text-left transition-all hover:border-blue-500 hover:bg-blue-50 disabled:opacity-60 disabled:cursor-not-allowed"
                                                onClick={() => {
                                                    runPromptByIndex(prompt.index);
                                                    setShowAvailablePrompts(false);
                                                }}
                                                disabled={isLoading}
                                            >
                                                <span className="font-bold text-gray-600 min-w-[2rem] mt-0.5">
                                                    #{i + 1}
                                                </span>
                                                <span className="flex-1 text-sm leading-relaxed text-gray-800">
                                                    {prompt.text}
                                                </span>
                                            </button>
                                        ))}
                                    </div>
                                )}
                            </div>
                        )}

                        {promptWorkspaces.length > 0 ? (
                            <div className="flex flex-col gap-2">
                                {promptWorkspaces.map((workspace, i) => (
                                    <button
                                        key={i}
                                        className={`flex items-center gap-3 p-3 border-2 rounded-md cursor-pointer text-left transition-all ${
                                            i === currentWorkspaceIndex
                                                ? "bg-blue-500 text-white border-blue-700"
                                                : "bg-white border-blue-300 hover:bg-blue-50 hover:border-blue-500"
                                        }`}
                                        onClick={() => switchToWorkspace(i)}
                                    >
                                        <span
                                            className={`font-bold min-w-[2rem] ${
                                                i === currentWorkspaceIndex ? "text-white" : "text-gray-600"
                                            }`}
                                        >
                                            #{i + 1}
                                        </span>
                                        <span className="flex-1 text-sm leading-relaxed overflow-hidden text-ellipsis whitespace-nowrap">
                                            {workspace.promptData.prompt_tokens.slice(0, 8).join(" ")}...
                                        </span>
                                        <span
                                            className={`text-xl font-bold cursor-pointer px-1 py-0.5 rounded-full transition-colors ${
                                                i === currentWorkspaceIndex
                                                    ? "text-white hover:bg-white/20"
                                                    : "text-gray-600 hover:bg-red-100 hover:text-red-600"
                                            }`}
                                            onClick={(e) => {
                                                e.stopPropagation();
                                                closeWorkspace(i);
                                            }}
                                        >
                                            ×
                                        </span>
                                    </button>
                                ))}
                            </div>
                        ) : (
                            <div className="py-8 text-center text-gray-600 italic">
                                No prompts loaded. Click &quot;Add Prompt&quot; to start.
                            </div>
                        )}
                    </div>

                    <SavedMasksPanel ref={savedMasksPanelRef} onApplyMask={applyMaskAsAblation} />
                </div>

                <div className="flex gap-4 min-h-[70vh]">
                    <div className="p-2 flex-[0_0_50%] max-w-[50%] sticky top-4 self-start max-h-[calc(100vh-2rem)] overflow-y-auto">
                        {result && currentPromptId && (
                            <>
                                <ComponentHeatmap
                                    result={result}
                                    promptId={currentPromptId}
                                    onCellClick={openPopup}
                                    onMaskCreated={refreshSavedMasks}
                                />

                                <DisabledComponentsPanel
                                    promptTokens={result.prompt_tokens}
                                    isLoading={isLoading}
                                    onSendAblation={sendAblation}
                                    onToggleComponent={toggleComponentDisabled}
                                />
                            </>
                        )}
                    </div>

                    <div className="flex-1 overflow-y-auto pr-4">
                        {result?.full_run_token_logits && (
                            <OriginalPredictions
                                tokenLogits={result.full_run_token_logits}
                                promptTokens={result.prompt_tokens}
                                title="Original Model Predictions"
                            />
                        )}

                        {result?.ci_masked_token_logits && (
                            <OriginalPredictions
                                tokenLogits={result.ci_masked_token_logits}
                                promptTokens={result.prompt_tokens}
                                title="Original <strong>CI Masked</strong> Model Predictions"
                            />
                        )}

                        {result &&
                            ablationResults.map((ablationResult) => (
                                <AblationPredictions
                                    key={ablationResult.id}
                                    tokenLogits={ablationResult.tokenLogits}
                                    promptTokens={result.prompt_tokens}
                                    appliedMask={ablationResult.applied_mask}
                                    maskOverride={ablationResult.maskOverride}
                                />
                            ))}
                    </div>
                </div>

                <ComponentDetailModal
                    onClose={closePopup}
                    onToggleComponent={toggleComponentDisabled}
                    isComponentDisabled={isComponentDisabled}
                    promptId={currentPromptId}
                />
            </div>
        </main>
    );
}
