// spd/app/frontend-react/src/App.tsx
import { useState, useEffect } from "react";
import "./App.css";
import { getStatus, loadRun, loadClusterRun } from "./api";
import type { Status } from "./api";
import { ComponentStateProvider } from "./stores/componentState";
import { ActivationContextsTab } from "./components/ActivationContextsTab";
import { InterventionsTab } from "./components/InterventionsTab";
import { ClusterDashboardTab } from "./components/ClusterDashboardTab";

function App() {
  const [inputTrainWandbRunId, setInputTrainWandbRunId] = useState<string>("");
  const [loadingTrainRun, setLoadingTrainRun] = useState(false);

  const [status, setStatus] = useState<Status | null>(null);

  const [clusterWandbRunPath, setClusterWandbRunPath] = useState<string | null>(
    null
  );
  const [clusterIteration, setClusterIteration] = useState<number | null>(null);
  const [loadingClusterRun, setLoadingClusterRun] = useState(false);

  const [activeTab, setActiveTab] = useState<string | null>(null);

  const loadStatus = async () => {
    const statusData = await getStatus();
    setStatus(statusData);
    if (!statusData.train_run) {
      return;
    }
    if (!statusData.cluster_run) {
      return;
    }
    setClusterWandbRunPath(statusData.cluster_run.wandb_path);
  };

  useEffect(() => {
    setInterval(loadStatus, 3000);
  }, []);

  const handleLoadRun = async () => {
    if (!inputTrainWandbRunId?.trim()) return;

    setStatus(null);
    setLoadingTrainRun(true);
    try {
      await loadRun(inputTrainWandbRunId);
    } catch (error) {
      console.error("Error loading run", error);
    } finally {
      setLoadingTrainRun(false);
    }
    await loadStatus();
  };

  const handleLoadClusterRun = async () => {
    console.log("loading cluster run", clusterWandbRunPath, clusterIteration);
    const canLoadCluster =
      clusterWandbRunPath !== null && clusterIteration !== null;
    if (!canLoadCluster) {
      console.log("cannot submit cluster settings", {
        clusterWandbRunPath,
        clusterIteration,
      });
      return;
    }

    setLoadingClusterRun(true);
    await loadClusterRun(
      clusterWandbRunPath!.split("/").pop()!,
      clusterIteration!
    );
    setLoadingClusterRun(false);

    await loadStatus();
  };

  useEffect(() => {
    loadStatus();
  }, []);

  return (
    <ComponentStateProvider>
      <div className="app-layout">
        <aside className="sidebar">
          <div className="run-selector">
            <label htmlFor="wandb-run-id">W&B Run ID</label>
            <div className="input-group">
              <input
                type="text"
                id="wandb-run-id"
                value={inputTrainWandbRunId}
                onChange={(e) => setInputTrainWandbRunId(e.target.value)}
                disabled={loadingTrainRun}
                placeholder="Select or enter run ID"
              />
              <button
                onClick={handleLoadRun}
                disabled={loadingTrainRun || !inputTrainWandbRunId?.trim()}
              >
                {loadingTrainRun ? "Loading..." : "Load Run"}
              </button>
            </div>
          </div>

          <div className="tab-navigation">
            {status?.train_run && (
              <>
                <button
                  className={`tab-button ${
                    activeTab === "activation-contexts" ? "active" : ""
                  }`}
                  onClick={() => setActiveTab("activation-contexts")}
                >
                  Activation Contexts
                </button>

                <div className="cluster-settings">
                  <h4>Cluster Settings</h4>
                  <form
                    onSubmit={(e) => {
                      e.preventDefault();
                      handleLoadClusterRun();
                    }}
                  >
                    <label>
                      Clustering Run
                      <select
                        value={clusterWandbRunPath || ""}
                        onChange={(e) => setClusterWandbRunPath(e.target.value)}
                      >
                        {status?.train_run?.available_cluster_runs?.map((run) => (
                          <option key={run} value={run}>
                            {run}
                          </option>
                        ))}
                      </select>
                    </label>
                    <div className="settings-grid">
                      <label>
                        Iteration
                        <input
                          type="number"
                          value={clusterIteration || ""}
                          onChange={(e) =>
                            setClusterIteration(
                              e.target.value ? parseInt(e.target.value) : null
                            )
                          }
                        />
                      </label>
                    </div>
                    <button
                      className="cluster-load"
                      type="submit"
                      disabled={loadingClusterRun}
                    >
                      Load Cluster Run
                    </button>
                  </form>
                </div>

                <button
                  className={`tab-button ${
                    activeTab === "ablation" ? "active" : ""
                  }`}
                  disabled={!status?.cluster_run}
                  onClick={() => setActiveTab("ablation")}
                >
                  Component Ablation
                  {loadingClusterRun && <div className="spinner"></div>}
                </button>

                <button
                  className={`tab-button ${
                    activeTab === "cluster-dashboard" ? "active" : ""
                  }`}
                  disabled={!status?.cluster_run}
                  onClick={() => setActiveTab("cluster-dashboard")}
                >
                  Cluster Dashboard
                  {loadingClusterRun && <div className="spinner"></div>}
                </button>
              </>
            )}
          </div>
        </aside>
        <div className="main-content">
          {status?.train_run && (
            <div
              style={{
                display: activeTab === "activation-contexts" ? "block" : "none",
              }}
            >
              <ActivationContextsTab
                availableComponentLayers={status.train_run.component_layers}
              />
            </div>
          )}
          {status?.train_run && activeTab === "ablation" && (
            <div>
              {status?.cluster_run && clusterIteration !== null ? (
                <InterventionsTab cluster_run={status.cluster_run} iteration={clusterIteration} />
              ) : (
                <div className="status">No cluster run selected.</div>
              )}
            </div>
          )}
          {status?.train_run && activeTab === "cluster-dashboard" && (
            <div>
              {status?.cluster_run && clusterIteration !== null ? (
                <ClusterDashboardTab iteration={clusterIteration} />
              ) : (
                <div className="status">No cluster run selected.</div>
              )}
            </div>
          )}
        </div>
      </div>
    </ComponentStateProvider>
  );
}

export default App;

// app/frontend/src/App.svelte
<script lang="ts">
    import type { Status } from "./lib/api";
    import * as api from "./lib/api";
    import { onMount } from "svelte";

    import ActivationContextsTab from "./lib/components/ActivationContextsTab.svelte";
    import { parseWandbRunPath } from "./lib";

    let loadingTrainRun: boolean = false;

    /** can be a wandb run path, or id. we sanitize this on sumbit */
    let trainWandbRunEntry: string | null = null;

    let status: Status = { train_run: null };

    async function loadStatus() {
        if (loadingTrainRun) return;

        console.log("getting status");

        try {
            status = await api.getStatus();
            loadingTrainRun = false;

            console.log("status:", status);
            if (!status.train_run) return;
            trainWandbRunEntry = status.train_run.wandb_path;
        } catch (error) {
            console.error("error loading status", error);
        }
    }

    async function loadRun() {
        const input = trainWandbRunEntry?.trim();
        if (!input) return;

        try {
            loadingTrainRun = true;
            status = { train_run: null };
            const wandbRunPath = parseWandbRunPath(input);
            console.log("loading run", wandbRunPath);
            trainWandbRunEntry = wandbRunPath;
            await api.loadRun(wandbRunPath);
            await loadStatus();
        } catch (error) {
            console.error("error loading run", error);
        } finally {
            loadingTrainRun = false;
        }
    }

    onMount(() => {
        loadStatus();
        setInterval(loadStatus, 5000);
    });

    let activeTab: "activation-contexts" | null = null;
</script>

<div class="app-layout">
    <aside class="sidebar">
        <div class="run-selector">
            <label for="wandb-run-id">W&B Run ID</label>
            <form on:submit|preventDefault={loadRun} class="input-group">
                <input
                    type="text"
                    id="wandb-run-id"
                    list="run-options"
                    bind:value={trainWandbRunEntry}
                    disabled={loadingTrainRun}
                    placeholder="Select or enter run ID"
                />
                <button type="submit" disabled={loadingTrainRun || !trainWandbRunEntry?.trim()}>
                    {loadingTrainRun ? "Loading..." : "Load Run"}
                </button>
            </form>
        </div>
        <div class="tab-navigation">
            {#if status.train_run}
                <button
                    class="tab-button"
                    class:active={activeTab === "activation-contexts"}
                    on:click={() => (activeTab = "activation-contexts")}
                >
                    Activation Contexts
                </button>
            {/if}
        </div>
        {#if status.train_run}
            <div class="config">
                <h4>Config</h4>
                <pre>{status.train_run?.config_yaml}</pre>
            </div>
        {/if}
    </aside>

    <!-- Main Content -->
    <div class="main-content">
        {#if status.train_run}
            <div class:hidden={activeTab !== "activation-contexts"}>
                <ActivationContextsTab />
            </div>
        {/if}
    </div>
</div>

<style>
    .app-layout {
        display: flex;
        min-height: 100vh;
    }

    .sidebar {
        background: #f8f9fa;
        border-right: 1px solid #dee2e6;
        padding: 1.5rem;
        display: flex;
        flex-direction: column;
        position: sticky;
        top: 0;
        height: 100vh;
        overflow-y: auto;
    }

    .main-content {
        flex: 1;
        min-width: 0;
        padding: 2rem;
        display: flex;
        flex-direction: column;
        gap: 1rem;
    }

    .tab-navigation {
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
    }

    .tab-button {
        padding: 0.75rem 1rem;
        background: white;
        border: 1px solid #dee2e6;
        border-radius: 6px;
        cursor: pointer;
        font-size: 0.9rem;
        font-weight: 500;
        color: #495057;
        transition: all 0.15s ease;
        text-align: left;
        display: flex;
        align-items: center;
        gap: 0.5rem;
    }
    .tab-button:disabled {
        opacity: 0.6;
        cursor: not-allowed;
    }

    .tab-button:hover {
        color: #007bff;
        background: #f8f9fa;
        border-color: #007bff;
    }

    .tab-button.active {
        color: white;
        background: #007bff;
        border-color: #007bff;
        box-shadow: 0 2px 4px rgba(0, 123, 255, 0.2);
    }

    .run-selector {
        margin-bottom: 1rem;
    }

    .run-selector label {
        display: block;
        margin-bottom: 0.5rem;
        font-weight: 600;
        color: #333;
        font-size: 0.9rem;
    }

    .input-group {
        display: flex;
        gap: 0.5rem;
    }

    .input-group input[type="text"] {
        flex: 1;
        padding: 0.5rem;
        border: 1px solid #ddd;
        border-radius: 4px;
        font-size: 1rem;
    }

    .input-group input[type="text"]:focus {
        outline: none;
        border-color: #4a90e2;
        box-shadow: 0 0 0 2px rgba(74, 144, 226, 0.1);
    }

    .input-group button {
        padding: 0.5rem 1rem;
        background-color: #4a90e2;
        color: white;
        border: none;
        border-radius: 4px;
        font-size: 1rem;
        cursor: pointer;
        white-space: nowrap;
    }

    .input-group button:hover:not(:disabled) {
        background-color: #357abd;
    }

    .input-group button:disabled {
        background-color: #ccc;
        cursor: not-allowed;
    }

    .config {
        margin-top: 1rem;
    }

    .config h4 {
        margin: 0;
    }

    .config pre {
        margin: 0;
        font-size: 0.8rem;
    }
</style>
