// spd/app/frontend/src/lib/components/TokenHighlights.svelte
<script lang="ts">
    export let rawText: string;
    export let offsetMapping: [number, number][];
    export let tokenCiValues: number[];
    export let activePosition: number = -1;
    export let precision: number = 3;

    type Segment = {
        text: string;
        ciValue: number;
        isActive: boolean;
    };

    const defaultHighlightColor = (importance: number): string => {
        const clamped = Math.min(Math.max(importance, 0), 1);
        const opacity = 0.15 + clamped * 0.35;
        return `rgba(0, 200, 0, ${opacity})`;
    };

    export let getHighlightColor: (importance: number) => string = defaultHighlightColor;

    $: segments = buildSegments(rawText, offsetMapping, tokenCiValues, activePosition);

    function buildSegments(
        text: string,
        offsets: [number, number][],
        ciValues: number[],
        activeIdx: number
    ): Segment[] {
        const result: Segment[] = [];
        let cursor = 0;

        offsets.forEach(([start, end], idx) => {
            if (cursor < start) {
                result.push({ text: text.slice(cursor, start), ciValue: 0, isActive: false });
            }

            const tokenText = text.slice(start, end);
            const ciValue = ciValues[idx] ?? 0;
            result.push({ text: tokenText, ciValue, isActive: idx === activeIdx });

            cursor = end;
        });

        if (cursor < text.length) {
            result.push({ text: text.slice(cursor), ciValue: 0, isActive: false });
        }

        return result.filter((segment) => segment.text.length > 0);
    }
</script>

<span class="token-highlights">
    {#each segments as segment, idx}
        {#if segment.ciValue > 0}
            <span
                class="token-highlight"
                class:active-token={segment.isActive}
                style={`background-color:${getHighlightColor(segment.ciValue)};`}
                title={`Importance: ${segment.ciValue.toFixed(precision)}`}
            >{segment.text}</span>
        {:else}
            {segment.text}
        {/if}
    {/each}
</span>

<style>
    .token-highlights {
        display: inline;
        white-space: pre-wrap;
    }

    .token-highlight {
        display: inline;
        padding: 2px 4px;
        border-radius: 3px;
    }

    .token-highlight.active-token {
        border: 2px solid rgba(255, 100, 0, 0.6);
    }
</style>

// spd/app/frontend-react/src/components/TokenHighlights.tsx
import React, { useMemo } from 'react';

interface Segment {
    text: string;
    ciValue: number;
    isActive: boolean;
}

interface TokenHighlightsProps {
    rawText: string;
    offsetMapping: [number, number][];
    tokenCiValues: number[];
    activePosition?: number;
    precision?: number;
    getHighlightColor?: (importance: number) => string;
}

const defaultHighlightColor = (importance: number): string => {
    const clamped = Math.min(Math.max(importance, 0), 1);
    const opacity = 0.15 + clamped * 0.35;
    return `rgba(0, 200, 0, ${opacity})`;
};

export const TokenHighlights: React.FC<TokenHighlightsProps> = ({
    rawText,
    offsetMapping,
    tokenCiValues,
    activePosition = -1,
    precision = 3,
    getHighlightColor = defaultHighlightColor,
}) => {
    const segments = useMemo(() => {
        const result: Segment[] = [];
        let cursor = 0;

        offsetMapping.forEach(([start, end], idx) => {
            if (cursor < start) {
                result.push({ text: rawText.slice(cursor, start), ciValue: 0, isActive: false });
            }

            const tokenText = rawText.slice(start, end);
            const ciValue = tokenCiValues[idx] ?? 0;
            result.push({ text: tokenText, ciValue, isActive: idx === activePosition });

            cursor = end;
        });

        if (cursor < rawText.length) {
            result.push({ text: rawText.slice(cursor), ciValue: 0, isActive: false });
        }

        return result.filter((segment) => segment.text.length > 0);
    }, [rawText, offsetMapping, tokenCiValues, activePosition]);

    return (
        <span className="token-highlights">
            {segments.map((segment, idx) => {
                if (segment.ciValue > 0) {
                    return (
                        <span
                            key={idx}
                            className={`token-highlight ${segment.isActive ? 'active-token' : ''}`}
                            style={{ backgroundColor: getHighlightColor(segment.ciValue) }}
                            title={`Importance: ${segment.ciValue.toFixed(precision)}`}
                        >
                            {segment.text}
                        </span>
                    );
                }
                return <span key={idx}>{segment.text}</span>;
            })}
        </span>
    );
};
